name: validators_brasil
description: Validação de Strings para dados brasileiros.
version: 1.0.0
repository: https://github.com/ogilvieira/validators-brasil

environment:
  sdk: '>=2.12.0'

dependencies:

dev_dependencies:
  test: ^1.24.0
