name: validators_brasil
description: Validators Brasil é um conjunto de métodos para validação de Strings de dados brasileiros com zero dependências
version: 1.0.1
repository: https://github.com/ogilvieira/validators-brasil

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
